### ISSUE TITLE
Crash for 18th Century "last modified" date

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jpylyzer#82]
I have a file whose *last modified* date is  ‎`01 ‎January ‎1768, ‏‎00:01:00` (don't even ask!).  This results in a ValueError:

    E:\testjp2hecker>f:\johan\pythoncode\jpylyzer\jpylyzer\jpylyzer.py test.xml
    <?xml version='1.0' encoding='UTF-8'?>
    Traceback (most recent call last):
      File "F:\johan\pythoncode\jpylyzer\jpylyzer\jpylyzer.py", line 683, in <module
    >
        main()
      File "F:\johan\pythoncode\jpylyzer\jpylyzer\jpylyzer.py", line 679, in main
        checkFiles(args.inputRecursiveFlag, args.inputWrapperFlag, jp2In)
      File "F:\johan\pythoncode\jpylyzer\jpylyzer\jpylyzer.py", line 605, in checkFi
    les
        xmlElement = checkOneFile(path)
      File "F:\johan\pythoncode\jpylyzer\jpylyzer\jpylyzer.py", line 329, in checkOn
    eFile
        "fileLastModified", time.ctime(os.path.getmtime(file)))
    ValueError: unconvertible time

Issue only happens under Windows (7); Linux (Mint) works fine.

Solution: add exception handler for this ValueError and/or impose lower limit on dates.

**Comment by bitsgalore** [comment]
Fix here:
<https://github.com/openpreserve/jpylyzer/commit/e0caaa4ef70c86b8276cf44170a74b0831997b3f>
